---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, Abhinav Jambulingam
# Created: Fall 2021
#
# Create EC2 Security Groups
#
# REQUIRES:
#   securityGroups - a list of dict's, each with name and optionally in_rules and/or out_rules
#   vpcId - AWS VPC ID for EC2
#   region - AWS region

- name: create a security group
  loop: "{{ securityGroups }}"
  loop_control:
    loop_var: sg
  amazon.aws.ec2_group:
    name: "{{ sg.name }}"
    description: "{{ sg.description }}"
    vpc_id: "{{ lookup('vars', vpcId) }}"
    region: "{{ region }}"
    rules: "{{ sg.in_rules | default([]) | asSecGroupRules }}"
    rules_egress: "{{ sg.out_rules | default([]) | asSecGroupRules }}"
...
