---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, Abhinav Jambulingam
# Created: Fall 2021
#
# Destroy EC2 Instances based on local variable file's stored IDs
#

- name: Read in variables from stored vars file
  ansible.builtin.include_vars: "{{ localVmVariables }}"

# - name: debug subnetCidrs
#   ansible.builtin.debug:
#     msg: "{{ lookup('vars', subnetCidrs) }}"

# - name: store in register ec2 group info
#   amazon.aws.ec2_group_info:
#     filters:
#       vpc-id: "{{ lookup('vars', vpcId) }}"
#   register: securityGroupInfo
#
# - name: Clean up security groups
#   amazon.aws.ec2_group:
#     group_id: "{{ item }}"
#     state: absent
#   loop: "{{ securityGroupInfo | json_query('security_groups[?group_name!=`default`].group_id') }}"

- name: Clean up provisioned Cloud Instances
  vars:
    ids: "{{ lookup('vars', runningInstanceIds, default=[]) }}"
  amazon.aws.ec2_instance:
    region: "{{ region }}"
    instance_ids: "{{ ids }}"
    state: absent

- name: Clean up provisioned subnets
  vars:
    myVpcId: "{{ vpcId | default('') }}"
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ myVpcId }}"
    cidr: "{{ item }}"
    state: absent
  loop: "{{ query('vars', subnetCidrs) | default([]) }}"
  when: "{{ myVpcId != '' }}"

- name: Clean up provisioned vpc
  vars:
    vpcName: "{{ vpc | default('') }}"
  amazon.aws.ec2_vpc_net:
    name: "{{ vpcName }}"
    state: absent
    cidr_block: "{{ vpcCIDR }}"
  when: "{{ vpcName != '' }}"

- name: delete local VM variables file to signify success
  ansible.builtin.file:
    path: "{{ localVmVariables }}"
    state: absent
...
